apiVersion: apps/v1
kind: Deployment
metadata:
  name: freestyle-api
  namespace: freestyle
  labels:
    app: freestyle-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: freestyle-api
  template:
    metadata:
      labels:
        app: freestyle-api
    spec:
      containers:
        - name: freestyle-api
          image: 017923816312.dkr.ecr.eu-west-1.amazonaws.com/freestyle:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4500
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
